# Generated by Django 6.1.1 on 2026-09-07 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastel', models.CharField(max_length=100)),
                ('sabor', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vainilla', 'Vainilla'), ('Fresa', 'Fresa'), ('Tres Leches', 'Tres Leches'), ('Red Velvet', 'Red Velvet'), ('Oreo', 'Oreo')], max_length=50)),
                ('tamano', models.CharField(choices=[('Chico', 'Chico'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20)),
                ('mensaje', models.CharField(blank=True, max_length=150)),
                ('fecha_entrega', models.DateField()),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Preparando', 'Preparando'), ('Listo', 'Listo'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
